excluded:
  - Pods
  - ___VARIABLE_productName___/Libraries
  - ___VARIABLE_productName___/Extensions
disabled_rules:
  - todo
  - line_length
  - trailing_whitespace
opt_in_rules:
  - force_cast
  - type_name
  - empty_count
  - force_unwrapping
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - nimble_operator
  - operator_usage_whitespace
  - first_where
  - fatal_error_message
  - let_var_whitespace
cyclomatic_complexity:
ignores_case_statements: true
identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
type_name:
  excluded:
    - T
    - E
    - D
    - P
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 800
  error: 1200
file_header: error
force_cast: warning
force_try: warning
