excluded:
  - Pods
  - ___VARIABLE_productName___/Libraries
  - ___VARIABLE_productName___/Extensions
disabled_rules:
  - line_length
  - trailing_whitespace
  - unused_optional_binding
  - identifier_name
  - private_outlet
  - trailing_closure
  - large_tuple
opt_in_rules:
  - force_cast
  - type_name
  - empty_count
  - force_unwrapping
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - object_literal
  - number_separator
  - fatal_error_message
  - let_var_whitespace
  - vertical_parameter_alignment_on_call
operator_whitespace:
  excluded:
    - ==
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 800
  error: 1200
force_cast: warning
force_try:
  severity: warning
number_separator:
  minimum_length: 5
reporter: "xcode"
custom_rules:
  localized_lensing:
    name: "Localized Lensing"
    regex: '\.~\s+Strings\s*\.'
    message: "Capture calls to `Strings` functions using `%~ { _ in Strings... }`"
    severity: error